#!/bin/bash

set -e

git rebase-stacked
if [ "x$1" != 'xlocal' ]; then
   arc diff --message=Rebase
fi


br=$(git first-downstream)

if [ "x$br" == "xnull" ]; then
  echo "Done"
else
  git co $br
  exec $0 $@
fi
