#!/bin/bash

set -e

git rebase-stacked
if [ "x$1" != 'xlocal' ]; then
   arc diff --message=Rebase
fi

curr_br=$(git rev-parse --abbrev-ref HEAD)

if [ "x$rebase_upto" == $curr_br ]; then
    echo "Reached rebase-target, stopping."
    exit 0
fi


br=$(git first-downstream)

if [ "x$br" == "xnull" ]; then
  echo "Done"
else
  git co $br
  exec $0 $@
fi
