#!/usr/bin/env bash

set -e
f=$(find /sys/devices -path '*/intel_backlight/*' -type f -name brightness)
curr=$(sudo cat $f)
if [ "x$1" == "x-" ]; then
    op='/'
else
    op='*'
fi
new_val=$(echo "flr($curr $op 2)" | bc)
sudo /usr/bin/env bash -c "echo $new_val > $f"
