#!/usr/bin/env bash

function do_max() {
    for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
        echo performance | sudo tee $i
    done
    for i in $(seq 1 7); do 
        echo 1 | sudo tee /sys/devices/system/cpu/cpu${i}/online
    done
}

function do_min() {
    for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
        echo powersave | sudo tee $i
    done
    for i in $(seq 1 7); do 
        echo 0 | sudo tee /sys/devices/system/cpu/cpu${i}/online
    done
}

function do_usr() {
    for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
        echo userspace | sudo tee $i
    done
    for i in $(seq 1 7); do 
        echo 1 | sudo tee /sys/devices/system/cpu/cpu${i}/online
    done
}

case "$1" in
    max) do_max ;;
    min) do_min ;;
    usr) do_usr ;;
    *) echo "Available options are {max|min}" && exit 1 ;;
esac


