#!/bin/bash

commit_count=${1:-1}

git branch -vv | jq --arg cc $commit_count -rRs \
   '. | split("\n")
      | map({raw: . | gsub(" +"; " ") | split(" ")})
      | map({
        current: (. | .raw[0] == "*"),
        branch: .raw[1],
        upstream: (.raw[3][1:][:-1])})
      | .[]
      | select(.current)
      | @text "rebase --onto \(.upstream) \(.branch)~\($cc) \(.branch)"' | xargs git
