#!/usr/bin/env bash

exclude="n"

if [ "x$4" != "x" ]; then
  exclude=$4
fi

awk -v b_start="${1}" -v b_end="${2}" -v b_match="${3}" -v b_exclude_matched="${exclude}" '

function print_frag() {
   if ( ( (matched == 1) && (b_exclude_matched == "n") ) ||
        ( (matched == 0) && (b_exclude_matched == "y") ) ) {
     for (i in a) print a[i];
   }
   delete a;
}

BEGIN {
  track = 0;
  matched = 0;
  if ( (b_exclude_matched != "n")  && (b_exclude_matched != "y") ) {
    print "Exclude arg must either be y or n (found: " b_exclude_matched ")";
    exit 1;
  }
}

{
  if ( track == 1 ) {
    if ( $0 ~ b_end ) {
      track = 0;
      print_frag();
    } else {
      a[NR] = $0;
      if ( $0 ~ b_match ) {
        matched = 1;
      }
    }
  }
  if ( track == 0 ) {
    if ( $0 ~ b_start ) {
      track = 1;
      matched = 0;
      a[0]=$0;
    }
  }
}

END { print_frag(); }
'
