#!/bin/bash

# export IDEA_JDK=/usr/lib/jvm/oracle-jdk-bin-1.8 # (used until 04 May 2022)
# export IDEA_JDK=/usr/lib/jvm/openjdk-bin-11
# export IDEA_JDK=/home/janmejay/tools/oracle_jdk/jdk-18.0.1.1
#/home/janmejay/tools/idea-IC-163.9166.29/bin/idea.sh&
#/home/janmejay/tools/idea-IC-171.4694.70/bin/idea.sh&
#/home/janmejay/tools/idea-IC-172.4155.36/bin/idea.sh&
#/home/janmejay/tools/idea-IC-173.3727.127/bin/idea.sh&
#/home/janmejay/tools/idea-IC-181.5281.24/bin/idea.sh&
#/home/janmejay/tools/idea-IC-181.5540.7/bin/idea.sh & # (last good before scala upgrade on master)
#/home/janmejay/tools/idea-IC-191.7479.19/bin/idea.sh &
# /home/janmejay/tools/idea-IC-191.6183.87/bin/idea.sh & # (used until 04 May 2022)
/home/janmejay/tools/idea-IC-221.5080.210/bin/idea.sh &

#/home/janmejay/tools/idea-IC-182.4892.20/bin/idea.sh & # does not accept Set(classOf[TransactionRaceLostException]) for Class[_ <: Throwable] => Boolean


disown
