#!/bin/bash

export IDEA_JDK=/usr/lib/jvm/oracle-jdk-bin-1.8
#/home/janmejay/tools/idea-IC-163.9166.29/bin/idea.sh&
#/home/janmejay/tools/idea-IC-171.4694.70/bin/idea.sh&
#/home/janmejay/tools/idea-IC-172.4155.36/bin/idea.sh&
#/home/janmejay/tools/idea-IC-173.3727.127/bin/idea.sh&
#/home/janmejay/tools/idea-IC-181.5281.24/bin/idea.sh&
/home/janmejay/tools/idea-IC-181.5540.7/bin/idea.sh &

disown
