#!/bin/bash

jaildir=${jaildir:-$1}

function mount_if_not_mounted() {
    mount | grep -q $1
    if [ $? -eq 0 ] ; then
        echo "$1 is already mounted, not mounting $2 at $1"
    else
        sudo mount -t $2 $2 $1
    fi
}

if [[ -d $jaildir ]] ; then 
    echo "jaildir set to $jaildir, chrooting now.";
    mount_if_not_mounted "$jaildir/proc" proc
    mount_if_not_mounted "$jaildir/dev/pts" devpts

    sudo chroot $jaildir /bin/bash --login

    sudo umount "$jaildir/dev/pts" -l
    sudo umount "$jaildir/proc"
else
    echo "jaildir must be set, exiting."
fi

