#!/usr/bin/env bash

# set -x

if [ "x$1" == 'x' ]; then
    name=$(xclip -o)
else
    name=$(basename $1)
fi

if [ "x$name" == 'x' ]; then
    echo "No file, aborting." 1>&2
    exit 1
fi

echo -e "Looking up '$name'\n"

echo 'Owner:'

find . -name $name -exec file_in_path {} OWNERS \; | xargs cat
