#!/bin/zsh

xmm

touchpad-reset

wicd-client -t >/dev/null 2>&1 &

if [ -e /dev/rt/swap ]; then
  sudo swapon /dev/rt/swap
fi

first_file_in_projects=$(find ~/projects -type f | head -1)

if [ "x$first_file_in_projects" = 'x' ]; then
  sudo mount -o bind /mnt/work/projects ~/projects
fi

xset -dpms

parcellite

disown
