#!/bin/zsh

# xmm

touchpad-reset

sudo mkdir /var/run/connman

echo 'nameserver 127.0.0.1' | sudo tee /etc/resolv.conf

sudo rc-service connman restart

connman-gtk >/dev/null 2>&1 &

if [ -e /dev/rt/swap ]; then
  sudo swapon /dev/rt/swap
fi

first_file_in_projects=$(find ~/projects -type f | head -1)

if [ "x$first_file_in_projects" = 'x' ]; then
  sudo mount -o bind /mnt/work/projects ~/projects
fi

xset -dpms

~/projects/CopyQ/build/copyq &

disown

echo never \
    | sudo tee /sys/kernel/mm/transparent_hugepage/enabled \
    | sudo tee /sys/kernel/mm/transparent_hugepage/defrag

# xinput set-prop  11 141 1.3 0 0 0 1.3 0 0 0 1.3 # dell wireless mouse accel
# xinput set-prop 11 274 12 1 1 # useless, aim was to bump up scroll-wheel speed
