#!/bin/zsh

xmm

synclient ClickFinger2=0
synclient ClickFinger3=3 #because thumb becomes the 3rd finger touches down on a clickpad
synclient RightButtonAreaLeft=0
synclient RightButtonAreaTop=0
synclient MaxSpeed=8
synclient MinSpeed=1
synclient AccelFactor=0.1
synclient TapButton3=2 #middle click

syndaemon -i 1.0s -K -R -d

wicd-client -t >/dev/null 2>&1 &

disown

