#!/usr/bin/env bash

at=$1
if [ "x$at" == 'x' ]; then
    echo "Usage: split_json <num objs per array>"
    exit 1
fi

awk -v at=$at 'BEGIN { print "["; sd=1; }
               {
                 if (NR > 1 && (NR - 1) % at == 0)  {
                   print "]\n["
                   sd=1;
                 };
                 if (sd == 0) {
                   printf(",")
                 } else {
                   sd = 0
                 }
                 print $0
               }
               END { print "]"}'
