#!/bin/bash
echo "files to be added for versioning with svn are..."
svn st | grep ? | awk '{print $2}'
read -p "Add em all?? (Y/n):"
[ "$REPLY" == "n" ] || svn st | grep ? | awk '{print $2}' | xargs svn add