#!/usr/bin/env bash

file_name=~/tmp/gem_set/$1
link_location=~/.gem

if [ -d $file_name ] ; then
    rm $link_location
    ln -s $file_name $link_location
    echo "switched $link_location to $file_name"
else 
    echo "it seems directory: $file_name does not exist"
fi
