#!/usr/bin/env bash

read -rsn1 i

if ! [[ "x$i" =~ ^x[0-9]+$ ]] ; then
  echo "Given tray item 1-based index is not a number: $i"
fi

a=$1 # l => left click, r => right click

click=''
if [ "x$a" == 'xr' ]; then
  click="--click 3"
elif [ "x$a" == 'xl' ]; then
  click="--click 1"
fi

x=$(expr 3688 '+' '(' $i '*' 22 ')')
y=12

warpd --oneshot --move "$x $y" $click

if [ "x$click" == 'x' ]; then
  warpd --normal
fi
