#!/usr/bin/env python

import xmltodict
import json
import sys

with open(sys.argv[1], "r") as xml:
  xml_data=xml.read()

json_data = json.dumps(xmltodict.parse(xml_data))

with open(sys.argv[2], "w") as json:
  json.write(json_data)
