#!/bin/sh

if [ "x$loaded_xsessionrc" != 'xyes' ]; then
   export SCALA_HOME=/home/janmejay/tools/scala-2.12.2
   export PATH=~/.dev_utils:$JDK_HOME/bin:$PATH:/sbin:/usr/sbin:/var/lib/gems/1.8/bin:~/.gem/bin:~/tools/mysql/bin:/home/janmejay/go/bin:$SCALA_HOME/bin
   export GOPATH=/home/janmejay/projects/rubrik/sdmain1/src/go:/home/janmejay/go
   export loaded_xsessionrc='yes'
fi
